- name: "Creating ClusterClaim aap-done"
  kubernetes.core.k8s:
    state: present
    host: "{{ cluster_proxy.cluster_url }}"
    validate_certs: no
    api_key: "{{managed_serviceaccount.token}}"  
    definition:
      apiVersion: cluster.open-cluster-management.io/v1alpha1
      kind: ClusterClaim
      metadata:
        name: aap-done
- name: "Adding aap-done label"
  kubernetes.core.k8s:
    state: patched
    kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
    api_version: cluster.open-cluster-management.io/v1
    name: "{{ hostvars[inventory_hostname].cluster_name }}"
    kind: ManagedCluster
    validate_certs: no
    definition:
      metadata:
        labels:
          aap-done: ""
