- name: "Manage Clusters"
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - block: 
        - include_tasks: ../roles/k8s-cluster-access/tasks/get-temp-access.yml
          vars:
            rbac_template: ../k8s-rbac/cluster-admin
            serviceaccount_generate_name: "cluster-mgmt-"
            ttl: 60
        - include_role: 
            name: ../roles/create-namespace
          vars:
            namespace_name: "{{ namespace_to_add | default(omit) }}"
            state: "{{ state | default(omit) }}"
        - include_role:
            name: ../roles/mark-managedcluster-as-done
      always:
        - include_tasks: ../roles/k8s-cluster-access/tasks/remove-access.yml
          ignore_errors: true
